# Generated by Django 5.0.6 on 2024-07-24 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='birthday',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
